import 'package:flutter/material.dart';
import '../../config/asset_paths.dart';
import 'building_data.dart';

/// Comprehensive registry providing curriculum chapter buildings tailored
/// to the player's active subject (Mathematics, Physics, Chemistry, Computer Science, Biology, History)
/// and their active grade/class (Class 6 to Class 12).
abstract final class CurriculumBuildingsCatalog {
  /// Resolves 6 chapter buildings for the specified [subject] and [grade].
  static List<BuildingData> getBuildingsFor({
    required String subject,
    required String grade,
  }) {
    final cleanSubject = subject.trim().toLowerCase();
    final cleanGrade = grade.trim().toLowerCase();

    if (cleanSubject.contains('math')) {
      return _getMathBuildings(cleanGrade);
    } else if (cleanSubject.contains('phys') || cleanSubject.contains('astro') || cleanSubject.contains('space')) {
      return _getPhysicsBuildings(cleanGrade);
    } else if (cleanSubject.contains('chem') || cleanSubject.contains('potion') || cleanSubject.contains('alchem')) {
      return _getChemistryBuildings(cleanGrade);
    } else if (cleanSubject.contains('comp') || cleanSubject.contains('prog') || cleanSubject.contains('code') || cleanSubject.contains('cs')) {
      return _getComputerScienceBuildings(cleanGrade);
    } else if (cleanSubject.contains('bio') || cleanSubject.contains('life')) {
      return _getBiologyBuildings(cleanGrade);
    } else if (cleanSubject.contains('hist') || cleanSubject.contains('civic') || cleanSubject.contains('social')) {
      return _getHistoryBuildings(cleanGrade);
    }

    // Default fallback to Class 10 Math
    return _getMathBuildings('class 10');
  }

  // ===========================================================================
  // MATHEMATICS CHAPTER BUILDINGS
  // ===========================================================================
  static List<BuildingData> _getMathBuildings(String grade) {
    final Color color = const Color(0xFFF2CA50);

    if (grade.contains('12')) {
      return [
        BuildingData(
          id: 'math_c12_rel_fn',
          name: 'Relations & Functions Hall',
          icon: Icons.alt_route_rounded,
          sprite: AssetPaths.buildingGrandHall,
          level: 1,
          subject: 'Mathematics',
          description: 'Class 12 • Chapter 1 & 2: Master Relations, Types of Functions, Composition, and Inverse Trigonometric Functions.',
          unlocked: true,
          xpRequired: 300,
          lessonsAvailable: 14,
          themeColor: color,
        ),
        BuildingData(
          id: 'math_c12_matrices',
          name: 'Matrices & Determinants Vault',
          icon: Icons.grid_4x4_rounded,
          sprite: AssetPaths.buildingLibrary,
          level: 1,
          subject: 'Mathematics',
          description: 'Class 12 • Chapter 3 & 4: Operations on Matrices, Transpose, Inverses, Adjoints, and Cramer\'s Determinant Rules.',
          unlocked: true,
          xpRequired: 300,
          lessonsAvailable: 12,
          themeColor: const Color(0xFFFAB387),
        ),
        BuildingData(
          id: 'math_c12_calculus',
          name: 'Calculus & Derivatives Spire',
          icon: Icons.trending_up_rounded,
          sprite: AssetPaths.buildingAstronomyTower,
          level: 1,
          subject: 'Mathematics',
          description: 'Class 12 • Chapter 5 & 6: Continuity, Differentiability, Chain Rule, Tangents, Normals, and Maxima/Minima.',
          unlocked: true,
          xpRequired: 300,
          lessonsAvailable: 16,
          themeColor: const Color(0xFF89DCEB),
        ),
        BuildingData(
          id: 'math_c12_integrals',
          name: 'Integrals & Areas Chamber',
          icon: Icons.all_inclusive_rounded,
          sprite: AssetPaths.buildingDuelArena,
          level: 1,
          subject: 'Mathematics',
          description: 'Class 12 • Chapter 7 & 8: Definite & Indefinite Integrals, Substitution, By Parts, and Area Under Curves.',
          unlocked: true,
          xpRequired: 300,
          lessonsAvailable: 15,
          themeColor: const Color(0xFFCBA6F7),
        ),
        BuildingData(
          id: 'math_c12_differential',
          name: 'Differential Equations Tower',
          icon: Icons.functions_rounded,
          sprite: AssetPaths.buildingAlchemyLab,
          level: 1,
          subject: 'Mathematics',
          description: 'Class 12 • Chapter 9: Order, Degree, Variable Separable, Homogeneous and Linear Differential Equations.',
          unlocked: true,
          xpRequired: 300,
          lessonsAvailable: 10,
          themeColor: const Color(0xFFA6E3A1),
        ),
        BuildingData(
          id: 'math_c12_vectors_3d',
          name: 'Vectors & 3D Geometry Sanctum',
          icon: Icons.view_in_ar_rounded,
          sprite: AssetPaths.buildingCodingTower,
          level: 1,
          subject: 'Mathematics',
          description: 'Class 12 • Chapter 10 & 11: Dot/Cross Products, Direction Cosines, Lines, Planes, and Probability Distributions.',
          unlocked: true,
          xpRequired: 300,
          lessonsAvailable: 14,
          themeColor: const Color(0xFF89B4FA),
        ),
      ];
    }

    if (grade.contains('11')) {
      return [
        BuildingData(
          id: 'math_c11_sets',
          name: 'Sets & Relations Spire',
          icon: Icons.pie_chart_rounded,
          sprite: AssetPaths.buildingGrandHall,
          level: 1,
          subject: 'Mathematics',
          description: 'Class 11 • Chapter 1 & 2: Sets, Subsets, Venn Diagrams, Cartesian Products, and Function Relations.',
          unlocked: true,
          xpRequired: 300,
          lessonsAvailable: 12,
          themeColor: color,
        ),
        BuildingData(
          id: 'math_c11_trig',
          name: 'Trigonometric Functions Hall',
          icon: Icons.change_history_rounded,
          sprite: AssetPaths.buildingLibrary,
          level: 1,
          subject: 'Mathematics',
          description: 'Class 11 • Chapter 3: Radian Angles, Trigonometric Identities, Transformation Formulae, and General Solutions.',
          unlocked: true,
          xpRequired: 300,
          lessonsAvailable: 14,
          themeColor: const Color(0xFFFAB387),
        ),
        BuildingData(
          id: 'math_c11_complex',
          name: 'Complex Numbers & Quadratics',
          icon: Icons.square_foot_rounded,
          sprite: AssetPaths.buildingAstronomyTower,
          level: 1,
          subject: 'Mathematics',
          description: 'Class 11 • Chapter 4 & 5: Imaginary Numbers, Argand Plane, Modulus, Conjugates, and Quadratic Roots.',
          unlocked: true,
          xpRequired: 300,
          lessonsAvailable: 10,
          themeColor: const Color(0xFF89DCEB),
        ),
        BuildingData(
          id: 'math_c11_permutations',
          name: 'Combinatorics & Binomial Hall',
          icon: Icons.casino_rounded,
          sprite: AssetPaths.buildingDuelArena,
          level: 1,
          subject: 'Mathematics',
          description: 'Class 11 • Chapter 7 & 8: Fundamental Counting Principle, Permutations (nPr), Combinations (nCr), and Binomial Expansions.',
          unlocked: true,
          xpRequired: 300,
          lessonsAvailable: 11,
          themeColor: const Color(0xFFCBA6F7),
        ),
        BuildingData(
          id: 'math_c11_series',
          name: 'Sequences & Straight Lines',
          icon: Icons.show_chart_rounded,
          sprite: AssetPaths.buildingAlchemyLab,
          level: 1,
          subject: 'Mathematics',
          description: 'Class 11 • Chapter 9 & 10: Arithmetic (AP) & Geometric Progressions (GP), Slopes, and Equation of Lines.',
          unlocked: true,
          xpRequired: 300,
          lessonsAvailable: 12,
          themeColor: const Color(0xFFA6E3A1),
        ),
        BuildingData(
          id: 'math_c11_conics_limits',
          name: 'Conic Sections & Limits Tower',
          icon: Icons.lens_blur_rounded,
          sprite: AssetPaths.buildingCodingTower,
          level: 1,
          subject: 'Mathematics',
          description: 'Class 11 • Chapter 11 & 13: Circles, Parabola, Ellipse, Hyperbola, Limits, Derivatives, and Probability.',
          unlocked: true,
          xpRequired: 300,
          lessonsAvailable: 14,
          themeColor: const Color(0xFF89B4FA),
        ),
      ];
    }

    if (grade.contains('9')) {
      return [
        BuildingData(
          id: 'math_c9_numbers',
          name: 'Real Number Systems Hall',
          icon: Icons.numbers_rounded,
          sprite: AssetPaths.buildingGrandHall,
          level: 1,
          subject: 'Mathematics',
          description: 'Class 9 • Chapter 1: Rational & Irrational Numbers, Real Number Lines, Laws of Exponents, and Rationalization.',
          unlocked: true,
          xpRequired: 300,
          lessonsAvailable: 10,
          themeColor: color,
        ),
        BuildingData(
          id: 'math_c9_polynomials',
          name: 'Polynomials & Algebra Sanctum',
          icon: Icons.auto_awesome_motion_rounded,
          sprite: AssetPaths.buildingLibrary,
          level: 1,
          subject: 'Mathematics',
          description: 'Class 9 • Chapter 2 & 4: Zeroes of Polynomials, Remainder & Factor Theorems, and Linear Equations in 2 Variables.',
          unlocked: true,
          xpRequired: 300,
          lessonsAvailable: 12,
          themeColor: const Color(0xFFFAB387),
        ),
        BuildingData(
          id: 'math_c9_coordinate',
          name: 'Coordinate Geometry Tower',
          icon: Icons.place_rounded,
          sprite: AssetPaths.buildingAstronomyTower,
          level: 1,
          subject: 'Mathematics',
          description: 'Class 9 • Chapter 3: Cartesian Coordinates, X-Y Axes, Quadrants, and Plotting Points on Cartesian Planes.',
          unlocked: true,
          xpRequired: 300,
          lessonsAvailable: 8,
          themeColor: const Color(0xFF89DCEB),
        ),
        BuildingData(
          id: 'math_c9_geometry',
          name: 'Euclid Lines & Angles Chamber',
          icon: Icons.polyline_rounded,
          sprite: AssetPaths.buildingDuelArena,
          level: 1,
          subject: 'Mathematics',
          description: 'Class 9 • Chapter 5 & 6: Euclid\'s Postulates, Intersecting Lines, Parallel Lines, Alternate Angles, and Triangles.',
          unlocked: true,
          xpRequired: 300,
          lessonsAvailable: 11,
          themeColor: const Color(0xFFCBA6F7),
        ),
        BuildingData(
          id: 'math_c9_triangles_quad',
          name: 'Triangles & Quadrilaterals',
          icon: Icons.change_history_rounded,
          sprite: AssetPaths.buildingAlchemyLab,
          level: 1,
          subject: 'Mathematics',
          description: 'Class 9 • Chapter 7 & 8: Congruence Criteria (SAS, ASA, SSS, RHS), Parallelograms, and Midpoint Theorem.',
          unlocked: true,
          xpRequired: 300,
          lessonsAvailable: 13,
          themeColor: const Color(0xFFA6E3A1),
        ),
        BuildingData(
          id: 'math_c9_circles_stats',
          name: 'Circles, Heron & Statistics Dome',
          icon: Icons.circle_outlined,
          sprite: AssetPaths.buildingCodingTower,
          level: 1,
          subject: 'Mathematics',
          description: 'Class 9 • Chapter 9-12: Chords & Subtended Angles, Heron\'s Triangle Formula, Surface Areas, and Statistics.',
          unlocked: true,
          xpRequired: 300,
          lessonsAvailable: 14,
          themeColor: const Color(0xFF89B4FA),
        ),
      ];
    }

    if (grade.contains('6') || grade.contains('7') || grade.contains('8')) {
      return [
        BuildingData(
          id: 'math_middle_numbers',
          name: 'Number Systems & Integers Hall',
          icon: Icons.calculate_rounded,
          sprite: AssetPaths.buildingGrandHall,
          level: 1,
          subject: 'Mathematics',
          description: '$grade • Chapter 1: Natural Numbers, Whole Numbers, Integers, Number Lines, and Order of Operations.',
          unlocked: true,
          xpRequired: 300,
          lessonsAvailable: 10,
          themeColor: color,
        ),
        BuildingData(
          id: 'math_middle_fractions',
          name: 'Fractions, Decimals & Ratios',
          icon: Icons.pie_chart_outline_rounded,
          sprite: AssetPaths.buildingLibrary,
          level: 1,
          subject: 'Mathematics',
          description: '$grade • Chapter 2: Proper/Improper Fractions, Decimal Conversions, Ratios, Unitary Method, and Percentages.',
          unlocked: true,
          xpRequired: 300,
          lessonsAvailable: 11,
          themeColor: const Color(0xFFFAB387),
        ),
        BuildingData(
          id: 'math_middle_algebra',
          name: 'Algebraic Expressions Sanctum',
          icon: Icons.functions_rounded,
          sprite: AssetPaths.buildingAstronomyTower,
          level: 1,
          subject: 'Mathematics',
          description: '$grade • Chapter 3: Constants & Variables, Linear Equations, Like/Unlike Terms, and Simple Word Problems.',
          unlocked: true,
          xpRequired: 300,
          lessonsAvailable: 10,
          themeColor: const Color(0xFF89DCEB),
        ),
        BuildingData(
          id: 'math_middle_geometry',
          name: 'Basic Geometry & Angles Chamber',
          icon: Icons.square_foot_rounded,
          sprite: AssetPaths.buildingDuelArena,
          level: 1,
          subject: 'Mathematics',
          description: '$grade • Chapter 4: Points, Lines, Rays, Angles, Types of Triangles, Quadrilaterals, and Circle Radius.',
          unlocked: true,
          xpRequired: 300,
          lessonsAvailable: 10,
          themeColor: const Color(0xFFCBA6F7),
        ),
        BuildingData(
          id: 'math_middle_mensuration',
          name: 'Perimeter, Area & Volume Tower',
          icon: Icons.aspect_ratio_rounded,
          sprite: AssetPaths.buildingAlchemyLab,
          level: 1,
          subject: 'Mathematics',
          description: '$grade • Chapter 5: Perimeter of Squares & Rectangles, Area of Triangles, Surface Area, and Volume of Cuboids.',
          unlocked: true,
          xpRequired: 300,
          lessonsAvailable: 12,
          themeColor: const Color(0xFFA6E3A1),
        ),
        BuildingData(
          id: 'math_middle_data',
          name: 'Data Handling & Probability Dome',
          icon: Icons.bar_chart_rounded,
          sprite: AssetPaths.buildingCodingTower,
          level: 1,
          subject: 'Mathematics',
          description: '$grade • Chapter 6: Bar Graphs, Histograms, Tally Charts, Mean, Median, Mode, and Basic Coin/Dice Probability.',
          unlocked: true,
          xpRequired: 300,
          lessonsAvailable: 9,
          themeColor: const Color(0xFF89B4FA),
        ),
      ];
    }

    // Default Class 10 Mathematics Chapter Set
    return [
      BuildingData(
        id: 'math_c10_real_numbers',
        name: 'Real Numbers & Primes Hall',
        icon: Icons.numbers_rounded,
        sprite: AssetPaths.buildingGrandHall,
        level: 1,
        subject: 'Mathematics',
        description: 'Class 10 • Chapter 1: Fundamental Theorem of Arithmetic, Prime Factorization, HCF & LCM, and Proofs of Irrationality.',
        unlocked: true,
        xpRequired: 300,
        lessonsAvailable: 10,
        themeColor: color,
      ),
      BuildingData(
        id: 'math_c10_polynomials_quad',
        name: 'Polynomials & Quadratics Sanctum',
        icon: Icons.auto_awesome_motion_rounded,
        sprite: AssetPaths.buildingLibrary,
        level: 1,
        subject: 'Mathematics',
        description: 'Class 10 • Chapter 2 & 4: Zeroes & Coefficients, Quadratic Equations (ax²+bx+c=0), Factoring, and the Quadratic Formula.',
        unlocked: true,
        xpRequired: 300,
        lessonsAvailable: 14,
        themeColor: const Color(0xFFFAB387),
      ),
      BuildingData(
        id: 'math_c10_linear_equations',
        name: 'Pair of Linear Equations Tower',
        icon: Icons.ssid_chart_rounded,
        sprite: AssetPaths.buildingAstronomyTower,
        level: 1,
        subject: 'Mathematics',
        description: 'Class 10 • Chapter 3: Graphical Solutions, Substitution, Elimination, and Consistent/Inconsistent Systems.',
        unlocked: true,
        xpRequired: 300,
        lessonsAvailable: 12,
        themeColor: const Color(0xFF89DCEB),
      ),
      BuildingData(
        id: 'math_c10_ap_triangles',
        name: 'Progressions & Triangles Chamber',
        icon: Icons.stairs_rounded,
        sprite: AssetPaths.buildingDuelArena,
        level: 1,
        subject: 'Mathematics',
        description: 'Class 10 • Chapter 5 & 6: Arithmetic Progressions (nth Term, Sum of n Terms), Thales Basic Proportionality & Similarity.',
        unlocked: true,
        xpRequired: 300,
        lessonsAvailable: 15,
        themeColor: const Color(0xFFCBA6F7),
      ),
      BuildingData(
        id: 'math_c10_trigonometry',
        name: 'Trigonometry & Heights Spire',
        icon: Icons.change_history_rounded,
        sprite: AssetPaths.buildingAlchemyLab,
        level: 1,
        subject: 'Mathematics',
        description: 'Class 10 • Chapter 8 & 9: Trigonometric Ratios (sin, cos, tan), Pythagorean Identities, and Heights & Distances.',
        unlocked: true,
        xpRequired: 300,
        lessonsAvailable: 16,
        themeColor: const Color(0xFFA6E3A1),
      ),
      BuildingData(
        id: 'math_c10_coord_stats',
        name: 'Coordinate Geometry & Statistics',
        icon: Icons.scatter_plot_rounded,
        sprite: AssetPaths.buildingCodingTower,
        level: 1,
        subject: 'Mathematics',
        description: 'Class 10 • Chapter 7, 12-14: Distance & Section Formulae, Circles, Surface Areas & Volumes, Mean, Median & Probability.',
        unlocked: true,
        xpRequired: 300,
        lessonsAvailable: 15,
        themeColor: const Color(0xFF89B4FA),
      ),
    ];
  }

  // ===========================================================================
  // PHYSICS CHAPTER BUILDINGS
  // ===========================================================================
  static List<BuildingData> _getPhysicsBuildings(String grade) {
    final Color color = const Color(0xFF89DCEB);

    if (grade.contains('11') || grade.contains('12')) {
      return [
        BuildingData(
          id: 'phys_kinematics',
          name: 'Kinematics & Dynamics Observatory',
          icon: Icons.speed_rounded,
          sprite: AssetPaths.buildingGrandHall,
          level: 1,
          subject: 'Physics',
          description: '$grade • Chapter 1-3: Vectors, Projectile Motion, Relative Velocity, Newton\'s Laws of Motion, and Friction.',
          unlocked: true,
          xpRequired: 300,
          lessonsAvailable: 14,
          themeColor: color,
        ),
        BuildingData(
          id: 'phys_energy_gravity',
          name: 'Work, Energy & Gravitation Vault',
          icon: Icons.public_rounded,
          sprite: AssetPaths.buildingLibrary,
          level: 1,
          subject: 'Physics',
          description: '$grade • Chapter 4-6: Work-Energy Theorem, Collisions, Universal Gravitation, Kepler\'s Laws, and Escape Velocity.',
          unlocked: true,
          xpRequired: 300,
          lessonsAvailable: 12,
          themeColor: const Color(0xFFFAB387),
        ),
        BuildingData(
          id: 'phys_thermodynamics',
          name: 'Thermodynamics & Kinetic Spire',
          icon: Icons.local_fire_department_rounded,
          sprite: AssetPaths.buildingAstronomyTower,
          level: 1,
          subject: 'Physics',
          description: '$grade • Chapter 7-9: Laws of Thermodynamics, Carnot Engine, Heat Transfer, and Kinetic Theory of Gases.',
          unlocked: true,
          xpRequired: 300,
          lessonsAvailable: 11,
          themeColor: const Color(0xFFF2CA50),
        ),
        BuildingData(
          id: 'phys_electrostatics',
          name: 'Electrostatics & Fields Chamber',
          icon: Icons.electric_bolt_rounded,
          sprite: AssetPaths.buildingDuelArena,
          level: 1,
          subject: 'Physics',
          description: '$grade • Chapter 10-12: Coulomb\'s Law, Gauss Theorem, Capacitance, Current Electricity, and Kirchhoff\'s Laws.',
          unlocked: true,
          xpRequired: 300,
          lessonsAvailable: 15,
          themeColor: const Color(0xFFCBA6F7),
        ),
        BuildingData(
          id: 'phys_magnetism_ac',
          name: 'Magnetism & AC Induction Tower',
          icon: Icons.waves_rounded,
          sprite: AssetPaths.buildingAlchemyLab,
          level: 1,
          subject: 'Physics',
          description: '$grade • Chapter 13-15: Biot-Savart Law, Faraday\'s Induction, AC Circuits, Transformers, and EM Waves.',
          unlocked: true,
          xpRequired: 300,
          lessonsAvailable: 13,
          themeColor: const Color(0xFFA6E3A1),
        ),
        BuildingData(
          id: 'phys_optics_modern',
          name: 'Optics & Quantum Physics Sanctum',
          icon: Icons.blur_on_rounded,
          sprite: AssetPaths.buildingCodingTower,
          level: 1,
          subject: 'Physics',
          description: '$grade • Chapter 16-18: Ray & Wave Optics, Photoelectric Effect, Bohr Model, Radioactivity & Semiconductors.',
          unlocked: true,
          xpRequired: 300,
          lessonsAvailable: 16,
          themeColor: const Color(0xFF89B4FA),
        ),
      ];
    }

    // Class 9-10 & Middle School Physics
    return [
      BuildingData(
        id: 'phys_c10_light',
        name: 'Light & Ray Optics Observatory',
        icon: Icons.wb_sunny_rounded,
        sprite: AssetPaths.buildingGrandHall,
        level: 1,
        subject: 'Physics',
        description: 'Class 10 • Chapter 10: Reflection in Spherical Mirrors, Refraction in Lenses, Mirror Formula, and Power of Lens.',
        unlocked: true,
        xpRequired: 300,
        lessonsAvailable: 14,
        themeColor: color,
      ),
      BuildingData(
        id: 'phys_c10_human_eye',
        name: 'Human Eye & Prisms Chamber',
        icon: Icons.remove_red_eye_rounded,
        sprite: AssetPaths.buildingLibrary,
        level: 1,
        subject: 'Physics',
        description: 'Class 10 • Chapter 11: Structure of Human Eye, Myopia, Hypermetropia, Dispersion in Glass Prisms, and Rainbows.',
        unlocked: true,
        xpRequired: 300,
        lessonsAvailable: 10,
        themeColor: const Color(0xFFFAB387),
      ),
      BuildingData(
        id: 'phys_c10_electricity',
        name: 'Electricity & Ohm\'s Law Spire',
        icon: Icons.electric_bolt_rounded,
        sprite: AssetPaths.buildingAstronomyTower,
        level: 1,
        subject: 'Physics',
        description: 'Class 10 • Chapter 12: Electric Current, Potential Difference, Ohm\'s Law (V=IR), Series/Parallel Circuits & Joule Heating.',
        unlocked: true,
        xpRequired: 300,
        lessonsAvailable: 15,
        themeColor: const Color(0xFFF2CA50),
      ),
      BuildingData(
        id: 'phys_c10_magnetism',
        name: 'Magnetic Effects & Motor Hall',
        icon: Icons.explore_rounded,
        sprite: AssetPaths.buildingDuelArena,
        level: 1,
        subject: 'Physics',
        description: 'Class 10 • Chapter 13: Magnetic Field Lines, Fleming\'s Left-Hand Rule, Electric Motors, and Electromagnetic Induction.',
        unlocked: true,
        xpRequired: 300,
        lessonsAvailable: 12,
        themeColor: const Color(0xFFCBA6F7),
      ),
      BuildingData(
        id: 'phys_c9_motion_force',
        name: 'Kinematics & Newton\'s Laws',
        icon: Icons.directions_run_rounded,
        sprite: AssetPaths.buildingAlchemyLab,
        level: 1,
        subject: 'Physics',
        description: 'Class 9 • Chapter 8 & 9: Distance, Displacement, Velocity, Acceleration, Newton\'s 3 Laws of Motion & Momentum.',
        unlocked: true,
        xpRequired: 300,
        lessonsAvailable: 13,
        themeColor: const Color(0xFFA6E3A1),
      ),
      BuildingData(
        id: 'phys_c9_gravity_energy',
        name: 'Gravitation, Work & Sound Dome',
        icon: Icons.volume_up_rounded,
        sprite: AssetPaths.buildingCodingTower,
        level: 1,
        subject: 'Physics',
        description: 'Class 9 • Chapter 10-12: Universal Law of Gravitation, Buoyancy & Density, Kinetic/Potential Energy & Sound Waves.',
        unlocked: true,
        xpRequired: 300,
        lessonsAvailable: 14,
        themeColor: const Color(0xFF89B4FA),
      ),
    ];
  }

  // ===========================================================================
  // CHEMISTRY CHAPTER BUILDINGS
  // ===========================================================================
  static List<BuildingData> _getChemistryBuildings(String grade) {
    final Color color = const Color(0xFFA6E3A1);

    if (grade.contains('11') || grade.contains('12')) {
      return [
        BuildingData(
          id: 'chem_atomic_bonding',
          name: 'Atomic Structure & Bonding Lab',
          icon: Icons.bubble_chart_rounded,
          sprite: AssetPaths.buildingGrandHall,
          level: 1,
          subject: 'Chemistry',
          description: '$grade • Chapter 1-3: Quantum Orbitals, Electronic Configuration, Lewis Structures, VSEPR & Hybridization.',
          unlocked: true,
          xpRequired: 300,
          lessonsAvailable: 14,
          themeColor: color,
        ),
        BuildingData(
          id: 'chem_thermo_equil',
          name: 'Thermodynamics & Equilibrium',
          icon: Icons.balance_rounded,
          sprite: AssetPaths.buildingLibrary,
          level: 1,
          subject: 'Chemistry',
          description: '$grade • Chapter 4-6: Enthalpy, Entropy, Gibbs Energy, Le Chatelier\'s Principle, and Ionic pH Equilibrium.',
          unlocked: true,
          xpRequired: 300,
          lessonsAvailable: 12,
          themeColor: const Color(0xFFFAB387),
        ),
        BuildingData(
          id: 'chem_electro_kinetics',
          name: 'Electrochemistry & Kinetics Spire',
          icon: Icons.battery_charging_full_rounded,
          sprite: AssetPaths.buildingAstronomyTower,
          level: 1,
          subject: 'Chemistry',
          description: '$grade • Chapter 7-9: Galvanic Cells, Nernst Equation, Rate of Reaction, Arrhenius Theory, and Activation Energy.',
          unlocked: true,
          xpRequired: 300,
          lessonsAvailable: 13,
          themeColor: const Color(0xFFF2CA50),
        ),
        BuildingData(
          id: 'chem_inorganic_blocks',
          name: 'p, d & f Block Inorganic Vault',
          icon: Icons.grid_on_rounded,
          sprite: AssetPaths.buildingDuelArena,
          level: 1,
          subject: 'Chemistry',
          description: '$grade • Chapter 10-12: Periodic Trends, Transition Elements, Lanthanoids, and Coordination Compounds.',
          unlocked: true,
          xpRequired: 300,
          lessonsAvailable: 14,
          themeColor: const Color(0xFFCBA6F7),
        ),
        BuildingData(
          id: 'chem_organic_hydrocarbons',
          name: 'Organic Hydrocarbons & Haloalkanes',
          icon: Icons.science_rounded,
          sprite: AssetPaths.buildingAlchemyLab,
          level: 1,
          subject: 'Chemistry',
          description: '$grade • Chapter 13-15: IUPAC Nomenclature, Isomerism, SN1/SN2 Reaction Mechanisms, and Alkanes/Alkenes.',
          unlocked: true,
          xpRequired: 300,
          lessonsAvailable: 16,
          themeColor: const Color(0xFF89DCEB),
        ),
        BuildingData(
          id: 'chem_oxygen_biomolecules',
          name: 'Aldehydes, Amines & Biomolecules',
          icon: Icons.medication_rounded,
          sprite: AssetPaths.buildingCodingTower,
          level: 1,
          subject: 'Chemistry',
          description: '$grade • Chapter 16-18: Alcohols, Phenols, Aldehydes, Ketones, Carboxylic Acids, Carbohydrates & Proteins.',
          unlocked: true,
          xpRequired: 300,
          lessonsAvailable: 15,
          themeColor: const Color(0xFF89B4FA),
        ),
      ];
    }

    // Class 9-10 Chemistry
    return [
      BuildingData(
        id: 'chem_c10_reactions',
        name: 'Chemical Reactions & Equations Lab',
        icon: Icons.science_rounded,
        sprite: AssetPaths.buildingGrandHall,
        level: 1,
        subject: 'Chemistry',
        description: 'Class 10 • Chapter 1: Balancing Chemical Equations, Types of Reactions (Combination, Decomposition, Displacement, Redox).',
        unlocked: true,
        xpRequired: 300,
        lessonsAvailable: 12,
        themeColor: color,
      ),
      BuildingData(
        id: 'chem_c10_acids_bases',
        name: 'Acids, Bases & Salts Chamber',
        icon: Icons.water_drop_rounded,
        sprite: AssetPaths.buildingLibrary,
        level: 1,
        subject: 'Chemistry',
        description: 'Class 10 • Chapter 2: Indicators, pH Scale, Neutralization, Bleaching Powder, Baking Soda, and Plaster of Paris.',
        unlocked: true,
        xpRequired: 300,
        lessonsAvailable: 14,
        themeColor: const Color(0xFFFAB387),
      ),
      BuildingData(
        id: 'chem_c10_metals',
        name: 'Metals & Metallurgy Foundry',
        icon: Icons.hardware_rounded,
        sprite: AssetPaths.buildingAstronomyTower,
        level: 1,
        subject: 'Chemistry',
        description: 'Class 10 • Chapter 3: Physical & Chemical Properties of Metals, Reactivity Series, Extraction of Metals, and Corrosion.',
        unlocked: true,
        xpRequired: 300,
        lessonsAvailable: 13,
        themeColor: const Color(0xFFF2CA50),
      ),
      BuildingData(
        id: 'chem_c10_carbon',
        name: 'Carbon & Its Compounds Spire',
        icon: Icons.diamond_rounded,
        sprite: AssetPaths.buildingDuelArena,
        level: 1,
        subject: 'Chemistry',
        description: 'Class 10 • Chapter 4: Covalent Bonding, Allotropes of Carbon, Saturated & Unsaturated Hydrocarbons, Functional Groups & Soaps.',
        unlocked: true,
        xpRequired: 300,
        lessonsAvailable: 16,
        themeColor: const Color(0xFFCBA6F7),
      ),
      BuildingData(
        id: 'chem_c9_matter',
        name: 'Matter & Solutions Observatory',
        icon: Icons.grain_rounded,
        sprite: AssetPaths.buildingAlchemyLab,
        level: 1,
        subject: 'Chemistry',
        description: 'Class 9 • Chapter 1 & 2: States of Matter, Evaporation, Homogeneous Mixtures, Colloids, Suspensions & Concentration.',
        unlocked: true,
        xpRequired: 300,
        lessonsAvailable: 11,
        themeColor: const Color(0xFF89DCEB),
      ),
      BuildingData(
        id: 'chem_c9_atoms_molecules',
        name: 'Atoms, Molecules & Periodic Vault',
        icon: Icons.auto_awesome_rounded,
        sprite: AssetPaths.buildingCodingTower,
        level: 1,
        subject: 'Chemistry',
        description: 'Class 9-10 • Chapter 3-5: Laws of Chemical Combination, Atomic Mass, Valency, Thomson/Rutherford Models & Periodic Table.',
        unlocked: true,
        xpRequired: 300,
        lessonsAvailable: 15,
        themeColor: const Color(0xFF89B4FA),
      ),
    ];
  }

  // ===========================================================================
  // COMPUTER SCIENCE & PROGRAMMING
  // ===========================================================================
  static List<BuildingData> _getComputerScienceBuildings(String grade) {
    final Color color = const Color(0xFF89B4FA);

    return [
      BuildingData(
        id: 'cs_logic_algorithms',
        name: 'Logic & Algorithm Academy',
        icon: Icons.alt_route_rounded,
        sprite: AssetPaths.buildingGrandHall,
        level: 1,
        subject: 'Computer Science',
        description: 'Computational Thinking: Flowcharts, Pseudocode, Time Complexity (Big-O), Binary Search & Sorting Algorithms.',
        unlocked: true,
        xpRequired: 300,
        lessonsAvailable: 12,
        themeColor: color,
      ),
      BuildingData(
        id: 'cs_syntax_variables',
        name: 'Syntax & Variable Foundry',
        icon: Icons.code_rounded,
        sprite: AssetPaths.buildingLibrary,
        level: 1,
        subject: 'Computer Science',
        description: 'Variables, Primitive Types (int, double, String, bool), Operators, String Interpolation, and Memory Stack.',
        unlocked: true,
        xpRequired: 300,
        lessonsAvailable: 10,
        themeColor: const Color(0xFFFAB387),
      ),
      BuildingData(
        id: 'cs_control_loops',
        name: 'Branching & Loop Citadel',
        icon: Icons.loop_rounded,
        sprite: AssetPaths.buildingAstronomyTower,
        level: 1,
        subject: 'Computer Science',
        description: 'If-Else Conditionals, Switch-Case Statements, While Loops, For-In Loops, and Recursion Termination.',
        unlocked: true,
        xpRequired: 300,
        lessonsAvailable: 14,
        themeColor: const Color(0xFFF2CA50),
      ),
      BuildingData(
        id: 'cs_oop_architecture',
        name: 'OOP & Class Sanctuary',
        icon: Icons.widgets_rounded,
        sprite: AssetPaths.buildingDuelArena,
        level: 1,
        subject: 'Computer Science',
        description: 'Object-Oriented Programming: Classes, Objects, Inheritance, Encapsulation, Polymorphism & Abstract Interfaces.',
        unlocked: true,
        xpRequired: 300,
        lessonsAvailable: 15,
        themeColor: const Color(0xFFCBA6F7),
      ),
      BuildingData(
        id: 'cs_data_structures',
        name: 'Data Structures Spire',
        icon: Icons.folder_special_rounded,
        sprite: AssetPaths.buildingAlchemyLab,
        level: 1,
        subject: 'Computer Science',
        description: 'Collections: Lists, Fixed/Growable Arrays, Sets, HashMaps (Key-Value Dictionaries), Stacks, Queues & Trees.',
        unlocked: true,
        xpRequired: 300,
        lessonsAvailable: 16,
        themeColor: const Color(0xFFA6E3A1),
      ),
      BuildingData(
        id: 'cs_networks_databases',
        name: 'Databases & Web APIs Tower',
        icon: Icons.cloud_sync_rounded,
        sprite: AssetPaths.buildingCodingTower,
        level: 1,
        subject: 'Computer Science',
        description: 'Async Programming (Futures, Streams), REST APIs, JSON Parsing, SQL Databases & Web Protocols.',
        unlocked: true,
        xpRequired: 300,
        lessonsAvailable: 14,
        themeColor: const Color(0xFF89DCEB),
      ),
    ];
  }

  // ===========================================================================
  // BIOLOGY & LIFE SCIENCES
  // ===========================================================================
  static List<BuildingData> _getBiologyBuildings(String grade) {
    final Color color = const Color(0xFF94E2D5);

    return [
      BuildingData(
        id: 'bio_cell_genetics',
        name: 'Cellular Biology Conservatory',
        icon: Icons.biotech_rounded,
        sprite: AssetPaths.buildingGrandHall,
        level: 1,
        subject: 'Biology',
        description: 'The Unit of Life: Cell Organelles, Mitochondria, Nucleus, Mitosis, Meiosis, DNA Replication & Chromosomes.',
        unlocked: true,
        xpRequired: 300,
        lessonsAvailable: 14,
        themeColor: color,
      ),
      BuildingData(
        id: 'bio_plant_physio',
        name: 'Plant Physiology & Flora Spire',
        icon: Icons.park_rounded,
        sprite: AssetPaths.buildingLibrary,
        level: 1,
        subject: 'Biology',
        description: 'Plant Kingdom: Photosynthesis, Chloroplasts, Xylem/Phloem Transport, Transpiration & Plant Hormones.',
        unlocked: true,
        xpRequired: 300,
        lessonsAvailable: 12,
        themeColor: const Color(0xFFA6E3A1),
      ),
      BuildingData(
        id: 'bio_human_systems',
        name: 'Human Anatomy & Systems Hall',
        icon: Icons.favorite_rounded,
        sprite: AssetPaths.buildingAstronomyTower,
        level: 1,
        subject: 'Biology',
        description: 'Human Body: Digestive System, Circulatory Flow, Respiratory Gas Exchange, Nervous System & Brain Anatomy.',
        unlocked: true,
        xpRequired: 300,
        lessonsAvailable: 16,
        themeColor: const Color(0xFFF28B82),
      ),
      BuildingData(
        id: 'bio_genetics_heredity',
        name: 'Heredity & Mendel\'s Laws Chamber',
        icon: Icons.hub_rounded,
        sprite: AssetPaths.buildingDuelArena,
        level: 1,
        subject: 'Biology',
        description: 'Genetics: Monohybrid & Dihybrid Crosses, Mendel\'s Laws of Inheritance, Sex Determination & Genetic Mutations.',
        unlocked: true,
        xpRequired: 300,
        lessonsAvailable: 13,
        themeColor: const Color(0xFFCBA6F7),
      ),
      BuildingData(
        id: 'bio_ecology_environment',
        name: 'Ecology & Biodiversity Sanctuary',
        icon: Icons.eco_rounded,
        sprite: AssetPaths.buildingAlchemyLab,
        level: 1,
        subject: 'Biology',
        description: 'Ecosystems: Food Chains, Trophic Levels, Carbon/Nitrogen Cycles, Biodiversity Conservation & Ozone Depletion.',
        unlocked: true,
        xpRequired: 300,
        lessonsAvailable: 11,
        themeColor: const Color(0xFFF2CA50),
      ),
      BuildingData(
        id: 'bio_health_microbiology',
        name: 'Microbiology & Immunity Dome',
        icon: Icons.healing_rounded,
        sprite: AssetPaths.buildingCodingTower,
        level: 1,
        subject: 'Biology',
        description: 'Health & Disease: Pathogens (Bacteria, Viruses, Fungi), Antibodies, Vaccines, Immune Defense & Public Sanitation.',
        unlocked: true,
        xpRequired: 300,
        lessonsAvailable: 12,
        themeColor: const Color(0xFF89B4FA),
      ),
    ];
  }

  // ===========================================================================
  // HISTORY & SOCIAL STUDIES
  // ===========================================================================
  static List<BuildingData> _getHistoryBuildings(String grade) {
    final Color color = const Color(0xFFFFD167);

    return [
      BuildingData(
        id: 'hist_ancient_empires',
        name: 'Ancient Civilizations Archive',
        icon: Icons.castle_rounded,
        sprite: AssetPaths.buildingGrandHall,
        level: 1,
        subject: 'History',
        description: 'Indus Valley, Mesopotamia, Ancient Egypt, Greece, Roman Empire & Vedic Era societal foundations.',
        unlocked: true,
        xpRequired: 300,
        lessonsAvailable: 12,
        themeColor: color,
      ),
      BuildingData(
        id: 'hist_medieval_trade',
        name: 'Medieval Kingdoms & Silk Road',
        icon: Icons.fort_rounded,
        sprite: AssetPaths.buildingLibrary,
        level: 1,
        subject: 'History',
        description: 'Delhi Sultanate, Mughal Empire, Byzantine Era, Feudal Europe, and the Great Maritime Silk Road.',
        unlocked: true,
        xpRequired: 300,
        lessonsAvailable: 14,
        themeColor: const Color(0xFFFAB387),
      ),
      BuildingData(
        id: 'hist_renaissance_rev',
        name: 'Renaissance & Revolutions Spire',
        icon: Icons.menu_book_rounded,
        sprite: AssetPaths.buildingAstronomyTower,
        level: 1,
        subject: 'History',
        description: 'European Renaissance, Printing Press, French Revolution, Russian Revolution & Industrial Innovation.',
        unlocked: true,
        xpRequired: 300,
        lessonsAvailable: 13,
        themeColor: const Color(0xFF89DCEB),
      ),
      BuildingData(
        id: 'hist_freedom_struggle',
        name: 'Nationalism & Freedom Chamber',
        icon: Icons.flag_rounded,
        sprite: AssetPaths.buildingDuelArena,
        level: 1,
        subject: 'History',
        description: 'Rise of Nationalism, Anti-Colonial Movements, Mahatma Gandhi, Civil Disobedience & Independence Movements.',
        unlocked: true,
        xpRequired: 300,
        lessonsAvailable: 15,
        themeColor: const Color(0xFFCBA6F7),
      ),
      BuildingData(
        id: 'hist_modern_world',
        name: 'World Wars & Global Treaties',
        icon: Icons.public_rounded,
        sprite: AssetPaths.buildingAlchemyLab,
        level: 1,
        subject: 'History',
        description: 'World War I & II, League of Nations, United Nations, Cold War Dynamics & Modern Global Alliances.',
        unlocked: true,
        xpRequired: 300,
        lessonsAvailable: 14,
        themeColor: const Color(0xFFA6E3A1),
      ),
      BuildingData(
        id: 'hist_civics_constitution',
        name: 'Constitution & Democracy Dome',
        icon: Icons.gavel_rounded,
        sprite: AssetPaths.buildingCodingTower,
        level: 1,
        subject: 'History',
        description: 'Democratic Institutions, Fundamental Rights, Separation of Powers, Judicial Systems & Global Citizenship.',
        unlocked: true,
        xpRequired: 300,
        lessonsAvailable: 12,
        themeColor: const Color(0xFF89B4FA),
      ),
    ];
  }
}
